/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03_scedu.serie.view;

import br.com.ifba.prg03_scedu.curriculo.controller.CurriculoIController;
import br.com.ifba.prg03_scedu.curriculo.entity.Curriculo;
import br.com.ifba.prg03_scedu.serie.controller.SerieIController;
import br.com.ifba.prg03_scedu.serie.entity.Serie;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author geovana
 */
@Component
public class SerieEditar extends javax.swing.JFrame {
    
   // @Autowired
    private final SerieIController controller;
    
    private final CurriculoIController curriculoController;
     
    private Serie serie = new Serie();
    
    private List<JCheckBox> checkBoxes;
    /**
     * Creates new form SerieEditar
     */
    public SerieEditar(SerieIController serieController, CurriculoIController curriculoController) {
        
        //Inicializa instancias dos controllers
        this.controller = serieController;
        this.curriculoController = curriculoController;
        initComponents();
       
        //Nao encerra o programa ao fechar a tela
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        //Cor de fundo da tela
        getContentPane().setBackground(new java.awt.Color(8, 102, 255));
        
        //Cor de fundo do painel
        jPanel1.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCadastrarSerie = new javax.swing.JLabel();
        lblNomeSerie = new javax.swing.JLabel();
        lblIdCurriculo = new javax.swing.JLabel();
        txtNomeSerie = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastrarSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCadastrarSerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrarSerie.setText("EDITAR SERIE");

        lblNomeSerie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeSerie.setText("Nome:");

        lblIdCurriculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdCurriculo.setText("Id Curriculo:");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCadastrarSerie)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdCurriculo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCadastrarSerie)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSerie)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdCurriculo)
                            .addComponent(btnSelecionar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(53, 53, 53)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            //Serie serie = new Serie();

            //Busca a serie no banco e verifica se foi encontrada
            serie = controller.findById(serie.getId());
            if(serie == null){
                JOptionPane.showMessageDialog(null, "Serie nao encontrada", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            
             //Define o nome da serie a partir do campo de texto da tela e verifica se estar vazio
            String nomeSerie = txtNomeSerie.getText();
            if(nomeSerie == null || nomeSerie.trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Insira o nome da serie!");
                return;
            }
            
            //Seta o noem da serie
            serie.setNome(nomeSerie);
            
            //Verifica se o curriculo eh nulo e inicia uma lista 
            if(serie.getCurriculo() == null) {
                serie.setCurriculo(new ArrayList<>());
            }
            
            boolean curriculoAssociado = false;
            //Percorre os checkBoxes pra encontrar os curriculos que foram selecionados
            for (JCheckBox checkBox : checkBoxes) {
                if(checkBox.isSelected()) {
                    //Converte o checkBox em long e busca o curriculo pelo id
                    Long curriculoId = Long.parseLong(checkBox.getText());
                    Curriculo curriculo = curriculoController.findById(curriculoId);
                    
                    // Verifica se o currículo já está associado a serie
                    if (serie.getCurriculo().contains(curriculo)) {
                        curriculoAssociado = true;
                          JOptionPane.showMessageDialog(null, "Este currículo já está associado a uma série.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    } else{
                        serie.getCurriculo().add(curriculo);
                    }
                }
            }
            controller.update(serie);
            if(curriculoAssociado){
                JOptionPane.showMessageDialog(null, "Alguns curriculos selecionados ja foram associados a serie,os demais foram adicionados.", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Série atualizada com sucesso!");
            }
            
        } catch (Exception error) {
            //Tratamento de execoes
            JOptionPane.showMessageDialog(null, error, "Erro ao cadastrar", JOptionPane.ERROR_MESSAGE);
        }

           /* //Busca o curriculo associado a serie e verifica se foi econtrado
            Curriculo curriculo = curriculoController.findById(curriculoId);
            if(curriculo == null){
                JOptionPane.showMessageDialog(null, "Curriculo nao encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            
            //Atualiza os dados de serie
            serie.setNome(txtNomeSerie.getText());
            
            //Verifica se a lista de curriculos esta nula e inicializa
            if(serie.getCurriculo() == null) {
                serie.setCurriculo((new ArrayList<>()));
            }
            //Adiciona o curriculo na lista de curriculos de serie
            serie.getCurriculo().add(curriculo);
            //Salva e atualiza
            controller.update(serie);
            JOptionPane.showMessageDialog(null, "Serie atualizada com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao editar serie" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            
        }*/
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here
        //Cria o JDialog
        JDialog dialog = new JDialog(this, "Selecione os IDs dos curriculos", true);
        dialog.setSize(300, 200);
        dialog.setLocationRelativeTo(btnSelecionar);

        List<Curriculo> curriculoLista = curriculoController.findAll();
        checkBoxes = new ArrayList<>();

        //Cria o painel de checkboxes
        JPanel panelCurriculos = new JPanel();
        panelCurriculos.setLayout(new GridLayout(0, 1));

        //Cria uma check box para cada curriculo do banco
        for (Curriculo curriculo : curriculoLista){
            //Converte o ID para String
            JCheckBox checkBox = new JCheckBox(curriculo.getId().toString());
            checkBoxes.add(checkBox);
            panelCurriculos.add(checkBox);
        }

        JScrollPane scrollPane = new JScrollPane(panelCurriculos);
        scrollPane.setPreferredSize(new Dimension(280, 150));

        dialog.add(scrollPane, BorderLayout.CENTER);

        JButton btnOk = new JButton("Ok");
        btnOk.addActionListener(e -> dialog.dispose());
        dialog.add(btnOk, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SerieEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SerieEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SerieEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SerieEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SerieEditar(serieController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastrarSerie;
    private javax.swing.JLabel lblIdCurriculo;
    private javax.swing.JLabel lblNomeSerie;
    private javax.swing.JTextField txtNomeSerie;
    // End of variables declaration//GEN-END:variables

    //Metodo para exportar os dados dessa tela para a tela de listar
    public Serie exportarDados(Serie series) {
        this.serie = series;
        return serie;
    }
}
